import { CHANGE_USERNAME_OR_PASSWORD,
  SIGN_IN,  SIGN_OUT,  MAKE_REDIRECT_UNACTIVE } from './authorization';
  
import { CHANGE_CHECKBOX_DATA_ARR,  CHANGE_CHECKBOX_DATA_SINGLE,
  CHANGE_INPUT_DATA_PAYMENT,  CHANGE_CHECKBOX_DATA_NAME,
  BIG_ACTION, GET_MORE,
  SWITCH_SEARCH,  GET_LOCATIONS,
  GET_LANGUAGES,  SORT,
  CHANGE_INPUT_STRING_VALUE } from './search';

import { GET_SKILLS,
    GET_PROMOTIONS, CHOOSE_CATEGORY,
    CHANGE_ACTIVE_PROMOTION_CATEGORY, CHOOSE_SKILL_CATEGORY,
    CHANGE_STR_INP_FOR_POSTJOB, CHANGE_CHECKBOX_FOR_POSTJOB,
    MAKE_ACTIVE_CREATING_SKILL_TEST,  MAKE_INACTIVE_CREATING_SKILL_TEST,
    CHOOSE_PROMOTION, POST_JOB,
    CLOSE_MODAL,  OPEN_MODAL,
    HIDE_MESSAGE_SUCCESS_POSTING, GET_SKILL_TAGS,
    OPEN_SKILL_TAGS_LIST, CLOSE_SKILL_TAGS_LIST,
    ADD_SKILL_TAG,  DELETE_SKILL_TAG } from './postJob';

import { GET_USERS_SKILLS,  CHOOSE_CATEGORY_FOR_SKILLS, 
  CHANGE_USERS_SKILL_CATEGORIES, CHANGE_USERS_SKILL_TAGS, 
  DELETE_SKILL_TAG_FOR_SKILLS, ADD_USERS_SKILLS,  
  DELETE_USERS_SKILLS,  EDIT_USERS_SKILLS,  
  GO_TO_THE_NEXT_STEP,  GO_TO_THE_PREVIOUS_STEP } from './skills';
  
// AUTHORIZATION

export {CHANGE_USERNAME_OR_PASSWORD};
export {SIGN_IN};
export {SIGN_OUT};
export {MAKE_REDIRECT_UNACTIVE};

// SEARCH

export {CHANGE_CHECKBOX_DATA_ARR};
export {CHANGE_CHECKBOX_DATA_SINGLE};
export {CHANGE_INPUT_DATA_PAYMENT};
export {CHANGE_CHECKBOX_DATA_NAME};
export {BIG_ACTION};
export {GET_MORE};
export {SWITCH_SEARCH};
export {GET_LOCATIONS};
export {GET_LANGUAGES};
export {SORT};
export {CHANGE_INPUT_STRING_VALUE};

// Getting skills for rendering on the PostJob Page
export {GET_SKILLS};

// Getting promotions for rendering on the PostJob Page
export {GET_PROMOTIONS};

// POST JOB
export {CHOOSE_CATEGORY};
export {CHANGE_ACTIVE_PROMOTION_CATEGORY};
export {CHOOSE_SKILL_CATEGORY};
export {CHANGE_STR_INP_FOR_POSTJOB};
export {CHANGE_CHECKBOX_FOR_POSTJOB};
export {MAKE_ACTIVE_CREATING_SKILL_TEST};
export {MAKE_INACTIVE_CREATING_SKILL_TEST};
export {CHOOSE_PROMOTION};
export {POST_JOB};
export {CLOSE_MODAL};
export {OPEN_MODAL};
export {HIDE_MESSAGE_SUCCESS_POSTING};

// POST JOB, ADD SKILL TAG

export {GET_SKILL_TAGS};
export {OPEN_SKILL_TAGS_LIST};
export {CLOSE_SKILL_TAGS_LIST};
export {ADD_SKILL_TAG};
export {DELETE_SKILL_TAG};

// SKILLS

export {GET_USERS_SKILLS};
export {CHOOSE_CATEGORY_FOR_SKILLS};
export {CHANGE_USERS_SKILL_CATEGORIES};
export {CHANGE_USERS_SKILL_TAGS};
export {DELETE_SKILL_TAG_FOR_SKILLS};
export {ADD_USERS_SKILLS};
export {DELETE_USERS_SKILLS};
export {EDIT_USERS_SKILLS};
export {GO_TO_THE_NEXT_STEP};
export {GO_TO_THE_PREVIOUS_STEP};
